name: Terraform EKS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

    - name: Print AWS Environment Variables
      run: env | grep AWS

    # - name: Terraform Init and Apply for EC2
    #   working-directory: EC2
    #   run: |
    #     terraform init
    #     terraform apply -auto-approve \
    #       -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
    #       -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
    #       -var="region=${{ secrets.AWS_REGION }}"

    - name: Terraform Init and Apply for EKS
      working-directory: EKS
      run: |
        terraform init
        # terraform validate
        # terraform plan
        terraform apply -auto-approve \
          -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" 

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name EKS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Deploy Nginx to EKS
      run: |
        kubectl apply -f manifests/nginx-deployment.yaml
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
