name: Terraform EKS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init and Apply for EC2
      working-directory: EC2
      run: |
        terraform init
        terraform apply -auto-approve
        
    - name: Terraform Init and Apply for EKS
      working-directory: EKS
      run: |
        terraform init
        terraform apply -auto-approve

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --region us-west-2 --name eks-cluster

    - name: Deploy Nginx to EKS
      run: |
        kubectl apply -f manifests/nginx-deployment.yaml
